version: 2

formats: all

sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  install:
    - requirements: build_tools/requirements.txt
    - method: pip
      path: .
    - requirements: docs/requirements.txt
